### ISSUE TITLE
Model R: Homescreen w/ Locked+Not Connected flows

### ISSUE THREAD

**Issue by sime** [trezor/trezor-firmware#2330]
## Design
[Figma](https://www.figma.com/file/l0gG9XeRJ8FTDQ3cfb1wv9/Trezor-T%2C-Trezor-One?node-id=1830%3A10277)

|Locked|Not Connected|
|-|-|
|<img width="128" alt="Locked@2x" src="https://user-images.githubusercontent.com/216917/172593255-5c83dd24-2a2b-4a72-a0f3-e07e1d4eb481.png">|![not_connected](https://user-images.githubusercontent.com/216917/180737764-31c3a073-a935-41e5-820a-6a3ff8b0f665.png)|

### Default home screen
128x64:
![Homescreen](https://user-images.githubusercontent.com/216917/172592735-3efde758-5f47-4c3a-948b-e490eb42d826.png)

### Font
[Pixel Operator 8](https://github.com/trezor/trezor-firmware/issues/2269)

## User Story
As a Trezor user
I want to see the homescreen
So that I know my Trezor is ready to use.

## Acceptance Criteria
Given my Trezor has a PIN set
And I just connected it to power
When I connect it to a computer
Then I should see 'NOT CONNETED'
And Trezor Suite should not see my device

Given my Trezor is showing 'NOT CONNECTED'
When I tap any button
Then I should see PIN entry screen

Given my Trezor is 'NOT CONNECTED'
When I enter a valid PIN
Then Trezor Suite should see the Trezor

Given my Trezor has a PIN set
And the PIN has been entered once
When the auto lock time passes
Then the screen should dim
And I should see LOCKED on the screen

Given my Trezor is LOCKED
When I tap any button
Then I should be prompted for my pin
And the screen brightness is at 100%

Given my Trezor label is 'Vladimir'
Then the homescreen should show 'VLADIMIR'
And it should be uppercase

**Comment by grdddj** [comment]
Done in [1df6093](https://github.com/trezor/trezor-firmware/pull/2277/commits/1df60935e9965cea5192f537f917916344ddd781)

**Comment by sime** [comment]
**QA NOK**

* Missing the [default homescreen](https://user-images.githubusercontent.com/216917/172592735-3efde758-5f47-4c3a-948b-e490eb42d826.png).
* Distance between lock icon and text should be 4px
* Device label when not connected, should be 2px from the top
* 'Click to connect' should be 13px from the bottom (or 8px from 'Not Connected')

Screenshot for reference
![emu00000000](https://user-images.githubusercontent.com/216917/180738588-e1875238-abfb-4723-8da6-6b25b9b00118.png)

**Comment by grdddj** [comment]
> **QA NOK**
> 
>   Missing the [default homescreen](https://user-images.githubusercontent.com/216917/172592735-3efde758-5f47-4c3a-948b-e490eb42d826.png).
> 
>    Distance between lock icon and text should be 4px
> 
>   Device label when not connected, should be 2px from the top
> 
>   'Click to connect' should be 13px from the bottom (or 8px from 'Not Connected')

All should be addressed in [e9f2f7f](https://github.com/trezor/trezor-firmware/pull/2277/commits/e9f2f7f09443c7d9d9651c07812b9692f2e4ab49)

**Comment by sime** [comment]
**QA NOK**

@grdddj 

> Distance between lock icon and text should be 4px
Still not the case

`NOT CONNECTED` should have a `2px` padding between the letters, currently it is 1px.

`LOCKED` screen should show device label at the bottom, and nothing on the top.

**Comment by sime** [comment]
Reference image

![Image](https://user-images.githubusercontent.com/216917/181520889-223d3db7-91b4-4f7c-bd51-1a1fbaeff06f.png)

**Comment by grdddj** [comment]
> LOCKED screen should show device label at the bottom, and nothing on the top.

I saw it in Figma, but it is missing the `Click to unlock` thing there. Should all three things (locked, unlock and label) be put on the bottom?

**Comment by sime** [comment]
> > LOCKED screen should show device label at the bottom, and nothing on the top.
> 
> I saw it in Figma, but it is missing the `Click to unlock` thing there. Should all three things (locked, unlock and label) be put on the bottom?

Ah you are right. Leave the content of the `LOCKED` screen for now.
