### ISSUE TITLE
T2B1: homescreen flickering when Suite loading balances

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#2737]
When Suite is asking `Trezor` for data about its addresses, the homescreen experiences flickering, even on emulator

**Comment by grdddj** [comment]
No longer an issue (on emulator nor on hardware), most probably solved by a recent rebase on `master` which included some new code for handling the homescreen

**Comment by Hannsek** [comment]
I can still see it on the emulator.
<img width="771" alt="image" src="https://user-images.githubusercontent.com/57008159/214825011-5412128e-0760-4630-a894-0b8ec348746f.png">

**Comment by grdddj** [comment]
> I can still see it on the emulator. <img alt="image" width="771" src="https://user-images.githubusercontent.com/57008159/214825011-5412128e-0760-4630-a894-0b8ec348746f.png">

It is possible that you are using an old emulator - based on the job ID - `358...`. Unfortunately, newest pipelines do not build `ARM` emulator versions, there are some problems on the runners

**Comment by Hannsek** [comment]
This should be the newest one according to emulator.

**Comment by grdddj** [comment]
> This should be the newest one according to emulator.
> 
> Will the problems be solved?

Not sure, that is the question for adminkos - @vdovhanych
