### ISSUE TITLE
Cardano allows signing transactions with negative fees

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#438]
one such transaction is in the second test vector: https://github.com/trezor/trezor-firmware/blob/master/tests/device_tests/test_msg_cardano_sign_transaction.py#L61-L85
where the input value is 3169260, output is 3003112 and change is 1000000, for a total of -833852
This then ends up wrongly displayed as -1.166148 by `format_amount` which is not designed to work with negative values.

Presumably the network will reject such transactions, so the problem is not critical. Still, not great.

Care to take a look, @refi93 ?

**Comment by prusnak** [comment]
Negative values in `format_amount` fixed in https://github.com/trezor/trezor-firmware/issues/439

**Comment by mark-stopka** [comment]
So, is this fixed by #439 or it still needs additional work?

**Comment by prusnak** [comment]
@mark-stopka no, #439 only fixes negative numbers formatting - the issue itself is still not fixed

**Comment by gabrielKerekes** [comment]
@matejcik I think this can be closed now thanks to the Shelley update? Fee is no longer calculated from previous transactions, but is included in the transaction itself and it also can't be negative.

**Comment by matejcik** [comment]
agreed
