### ISSUE TITLE
Device freezes when displaying Bitcoin Cash Receiving address if I lock the computer screen

### ISSUE THREAD

**Issue by pankrats** [trezor/trezor-firmware#54]
Chrome, Linux
wallet.trezor.io

How to reproduce: 
1. Switch to Bitcoin Cash
2. Go to Receive tab 
3. Click on Show full address, wait for the address to appear on Trezor Screen
4. Lock your computer (for 1 min approx)
5. Restore your computer. 

Result: the screen becomes irresponsive. 

![screen](https://user-images.githubusercontent.com/31442634/46805460-62561600-cd65-11e8-9621-ad0d055820c8.gif)

**Comment by bosomt** [comment]
i was not able to reproduce it with latest 2.1.1
I think it was already fixed.
Please consider to closing this issue ;)

**Comment by pankrats** [comment]
It still happens. Please, keep the issue opened. 

Firmware 2.1.1.
Chrome, OS X

<img width="917" alt="Screenshot 2019-05-27 at 12 14 12" src="https://user-images.githubusercontent.com/31442634/58413409-fc5e9a80-8078-11e9-96a1-a114610be34b.png">

**Comment by ZdenekSL** [comment]
@pankrats Please retest with a new firmware.

**Comment by pankrats** [comment]
It still happens with 2.1.2 (core-2019-07-1ec5d0). 
important note: it works perfectly with WebUSB, the bug happens only when using **Bridge**

![2019-06-25 17 02 34](https://user-images.githubusercontent.com/31442634/60109815-4ff10080-976b-11e9-9bc8-3fb273d5fac7.jpg)

**Comment by prusnak** [comment]
> It works perfectly with WebUSB, the bug happens only when using Bridge

Sounds like a wallet issue then.
