### ISSUE TITLE
[T3W1] Device locks up when signing large message

### ISSUE THREAD

**Issue by fubuloubu** [trezor/trezor-firmware#6194]
**Describe the bug**
The wallet's UI permanently locks up on "Loading transaciton..." when signing a large EIP712 message.

**Firmware version and revision**

Device: Trezor Safe 7
Firmware version: 2.9.4.0

**Desktop/smartphone setup (please complete the following information):**
 - Wallet software: Ape (using `trezorlib`)
 - OS: Linux
 - Browser: n/a
 - Version: 0.20.0.dev0

**To Reproduce**

Install our Ape account plugin for trezor wallets: https://github.com/ApeWorX/ape-trezor (working PR for v0.20 upgrade: https://github.com/ApeWorX/ape-trezor/pull/50)
Install the latest version of the Python client library from this repo
Add an account from the Safe 7 (after setting it up)
Try to sign a large message with it from Ape

NOTE: Probably there's a much more minimal way to reproduce, but this is where I started

**Expected behavior**

If possible, it should just sign the message since this is a pernicious problem with using Trezor devices with production signing flows (e.g. w/ complex SafeTx messages).

However, best case scenario it should fail more gracefully if the payload size is too large.

When I do the same test w/ an older Model T, it just fails and the device is still responsive afterwards (doesn't need to be restarted). In python, it instead fails w/ "FirmwareError"

**Screenshots**

![Image](https://github.com/user-attachments/assets/38fd3464-5407-4445-975d-311da41b6407)

**Additional context**

Stack trace:

```py
# ape console
 In [1]: from eip712.common import create_safe_tx_def
 In [2]: safe_tx = create_safe_tx_def(contract_address="0x...", chain_id=1)(to="0x...", nonce=1, data=b"\x00" * 65535)
 In [3]: sig = trezor_acct.sign_message(safe_tx)
Enter code from Trezor: ...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
...

File ~/work/ApeWorX/plugins/trezor/ape_trezor/accounts.py:84, in TrezorAccount.sign_message(self, msg, **signer_options)
     82 if isinstance(msg, EIP712Message):
     83     data = _prepare_data_for_hashing(msg._body_)
---> 84     signed_msg = self.client.sign_typed_data(data)
     85 elif isinstance(msg, dict):
     86     # Raw typed data.
     87     signed_msg = self.client.sign_typed_data(msg)

File ~/work/ApeWorX/plugins/trezor/ape_trezor/client.py:147, in TrezorAccountClient.sign_typed_data(self, data)
    136 def sign_typed_data(self, data: dict) -> tuple[int, bytes, bytes]:
    137     """
    138     Sends a dict of data to the device and is much more obvious and secure
    139     than signing a hash alone.
   (...)
    145         tuple[int, bytes, bytes]: A signature tuple.
    146     """
--> 147     signed_data = sign_typed_data(self.session, self._account_hd_path.address_n, data)
    148     return extract_signature_vrs_bytes(signature_bytes=signed_data.signature)

File ~/work/Trezor/firmware/python/src/trezorlib/ethereum.py:381, in sign_typed_data(session, n, data, metamask_v4_compat, definitio
ns, show_message_hash)
    378         encoded_data = encode_data(member_data, member_typename)
    380     request = messages.EthereumTypedDataValueAck(value=encoded_data)
--> 381     response = session.call(request)
    383 return messages.EthereumTypedDataSignature.ensure_isinstance(response)


File ~/work/Trezor/firmware/python/src/trezorlib/transport/session.py:50, in Session.call(self, msg, expect, skip_firmware_version_c
heck, _passphrase_ack)
     48 if not skip_firmware_version_check:
     49     self.client.check_firmware_version()
---> 50 resp = self.call_raw(msg)
     52 while True:
     53     if isinstance(resp, messages.PinMatrixRequest):

File ~/work/Trezor/firmware/python/src/trezorlib/transport/session.py:75, in Session.call_raw(self, msg, timeout)
     74 def call_raw(self, msg: t.Any, timeout: float | None = None) -> t.Any:
---> 75     self._write(msg)
     76     return self._read(timeout)

File ~/work/Trezor/firmware/python/src/trezorlib/transport/session.py:311, in SessionV2._write(self, msg)
    309 def _write(self, msg: t.Any) -> None:
    310     LOG.debug("writing message %s", type(msg))
--> 311     self.channel.write(self.sid, msg)

File ~/work/Trezor/firmware/python/src/trezorlib/transport/thp/protocol_v2.py:96, in ProtocolV2Channel.write(self, session_id, msg)
     94 def write(self, session_id: int, msg: t.Any) -> None:
     95     msg_type, msg_data = self.mapping.encode(msg)
---> 96     self._encrypt_and_write(session_id, msg_type, msg_data)

File ~/work/Trezor/firmware/python/src/trezorlib/transport/thp/protocol_v2.py:322, in ProtocolV2Channel._encrypt_and_write(self, ses
sion_id, message_type, message_data, ctrl_byte)
    316 encrypted_message = self._noise.encrypt(data)
    318 header = MessageHeader(
    319     ctrl_byte, self.channel_id, len(encrypted_message) + CHECKSUM_LENGTH
    320 )
--> 322 thp_io.write_payload_to_wire_and_add_checksum(
    323     self.transport, header, encrypted_message
    324 )

File ~/work/Trezor/firmware/python/src/trezorlib/transport/thp/thp_io.py:40, in write_payload_to_wire_and_add_checksum(transport, he
ader, payload)
     38 data = payload + chksum
     39 if len(data) > MAX_PAYLOAD_LEN:
---> 40     raise RuntimeError("Message too large")
     41 write_payload_to_wire(transport, header, data)

RuntimeError: Message too large
```

**Comment by matejcik** [comment]
THP encrypted protocol has a hard limit of 64 kB per packet, so this is unlikely to get fixed the proper way without a redesign of the EIP712 flow.

(the answer here is, stop expecting your HWWs to sign payloads this big. but that's on the dapp developers)

---

what we very much need to fix is the fact that it locks up the Trezor.

**Comment by fubuloubu** [comment]
> redesign of the EIP712 flow.

> (the answer here is, stop expecting your HWWs to sign payloads this big. but that's on the dapp developers)

I somewhat frequently encounter this issue when using my Trezor in production signing flows (mostly on Safe) which means that I cannot sign important multisig txns with my Trezor device (whereas my Ledger devices never have a problem) 

> what we very much need to fix is the fact that it locks up the Trezor.

This is ultimately the issue I noticed, my older Model T doesn't have this lockup issue

**Comment by romanz** [comment]
Reproduced on T3W1 emulator using:
```
$ core/emu.py -sea &
$ trezorctl -vvv eth sign-typed-data -n m/44h/60h/0h/0/0 sign-typed-data.json
```

[`sign-typed-data.json.gz`](https://github.com/user-attachments/files/23860411/sign-typed-data.json.gz)

```
11.814 trezor.loop ERROR exception:
Traceback (most recent call last):
  File "trezor/loop.py", line 169, in _step
  File "trezor/wire/context.py", line 136, in with_context
  File "apps/ethereum/keychain.py", line 130, in wrapper
  File "apps/ethereum/sign_typed_data.py", line 51, in sign_typed_data
  File "apps/ethereum/sign_typed_data.py", line 127, in _generate_typed_data_hash
  File "apps/ethereum/sign_typed_data.py", line 217, in hash_struct
  File "apps/ethereum/sign_typed_data.py", line 390, in get_and_encode_data
  File "apps/ethereum/sign_typed_data.py", line 561, in get_value
  File "trezor/wire/context.py", line 70, in call
  File "trezor/wire/protocol_common.py", line 100, in call
  File "trezor/wire/thp/session_context.py", line 95, in read
  File "trezor/wire/thp/session_context.py", line 70, in _read_next_message
  File "trezor/wire/thp/channel.py", line 340, in decrypt_message
  File "trezor/wire/thp/channel.py", line 247, in recv_payload
  File "trezor/wire/thp/channel.py", line 294, in _get_reassembled_message
  File "trezor/wire/thp/interface_context.py", line 79, in get_next_message
  File "trezor/wire/thp/interface_context.py", line 137, in handle_packet
  File "trezor/wire/thp/channel.py", line 333, in reassemble
  File "trezor/wire/thp/channel.py", line 97, in handle_packet
  File "trezor/wire/thp/memory_manager.py", line 20, in get
AssertionError: 
```

**Comment by romanz** [comment]
Logs when lockup happens:

# Device log
```
13.457 trezor.wire.thp.channel INFO [USBIF] (cid: 81f7) write message: EthereumTypedDataValueRequest
13.457 trezor.wire.thp.channel DEBUG [USBIF] message contents:
EthereumTypedDataValueRequest {
    member_path: [1, 2]
}
13.457 trezor.wire.thp.channel DEBUG [USBIF] (cid: 81f7) encrypt
13.457 trezor.wire.thp.crypto DEBUG enc (key: 25c246e373fe5d1e913d8277a819d38504cac99719b4260385a67dff0e2c31e2, nonce: 22)
13.457 trezor.wire.thp.channel DEBUG [USBIF] (cid: 81f7) New nonce_send: 23
13.457 trezor.wire.thp.channel DEBUG [USBIF] (cid: 81f7) Sending 23 bytes, latency: 1 ms
13.457 trezor.loop DEBUG finish: <generator object '_write_packets' at 0x7f99bf7a1b60>
13.458 trezor.loop DEBUG finish: <generator object '_wait_for_packet' at 0x7f99bf7a3bc0>
13.459 trezor.wire.thp.channel DEBUG [USBIF] (cid: 81f7) get_channel_state: ENCRYPTED_TRANSPORT
13.459 trezor.wire.thp.channel DEBUG [USBIF] (cid: 81f7) reassembled valid ACK: 9 bytes
13.459 trezor.wire.thp.channel DEBUG [USBIF] Received ACK message with correct ack bit
13.459 trezor.wire.thp.session_context DEBUG [USBIF] Read - with expected types (468,) and expected type EthereumTypedDataValueAck
13.459 trezor.loop DEBUG finish: <generator object '_wait_for_packet' at 0x7f99bf7ab380>
13.459 trezor.wire.thp.channel DEBUG [USBIF] (cid: 81f7) get_channel_state: ENCRYPTED_TRANSPORT
13.459 trezor.wire.thp.channel DEBUG [USBIF] (cid: 81f7) reassembled valid message: 28 bytes
13.459 trezor.wire.thp.channel DEBUG [USBIF] (cid: 81f7) Received message with an unexpected sequential bit
13.459 trezor.wire.thp.channel DEBUG [USBIF] Writing ACK message to a channel with cid: 81f7, ack_bit: 1
43.419 trezor.loop DEBUG finish: <generator object '_timeout_task' at 0x7f99bf4fcb00>
53.419 trezor.loop DEBUG finish: <generator object '_timeout_task' at 0x7f99bf4ff520>
```

# Host log
```
[2025-12-02 12:46:33,888] trezorlib.transport.session DEBUG: reading message <class 'trezorlib.messages.EthereumTypedDataValueRequest'>
[2025-12-02 12:46:33,888] trezorlib.transport.session DEBUG: writing message <class 'trezorlib.messages.EthereumTypedDataValueAck'>
[2025-12-02 12:46:33,888] trezorlib.transport.session DEBUG: writing message <class 'trezorlib.messages.EndSession'>
```

The host is trying to end the session (after the `RuntimeException` is raised), but it uses the next THP SEQ bit (since the current `trezorlib` updates it before the message is sent):
https://github.com/trezor/trezor-firmware/blob/d5e3bbdfd74bb451c40a6caf0e874735eb368e65/python/src/trezorlib/transport/thp/protocol_v2.py#L310

Since the device failed to parse the "over-sized" `EthereumTypedDataValueAck` it still expects the previous SEQ bit - ignoring the `EndSession` request.

**Comment by romanz** [comment]
IIUC, since the error happens after encrypting the `EthereumTypedDataValueAck` message, the device won't be able to decrypt the next message (`EndSession`) since it didn't received the previous one (due to a reassembly failure), right?

CC: @M1nd3r

**Comment by fubuloubu** [comment]
@romanz @matejcik was this issue resolved in Firmware v2.9.6 release? Does the python SDK need an update to support the fix?

**Comment by M1nd3r** [comment]
@fubuloubu 

Tl;dr: I am sorry to disappoint you, but the issue was most likely not resolved in 2.9.6.

I am not 💯 in the loop on this issue. Similar/related issues have been solved (and released) since 2.9.4, but AFAIK they will not fix this issue:
- Make sure to increment THP `seq_bit`. https://github.com/trezor/trezor-firmware/pull/6138
- [T3W1] Don't stall THP handling during PIN unlock. https://github.com/trezor/trezor-firmware/pull/6145

The issue mentioned by @romanz above (https://github.com/trezor/trezor-firmware/pull/6195) was already merged into `main`, but it is not released yet. I am also not sure if it addresses the issue you're experiencing.

@romanz Do you have an update on this issue? Thanks

**Comment by romanz** [comment]
This is still unresolved - the issue here is that the client sends a message which cannot be decoded on the device (since it's length is above [the maximal supported size](https://github.com/trezor/trezor-firmware/blob/26df4197fe5c3f85d8a9af4ca688e3f6c9b59707/core/src/trezor/wire/thp/memory_manager.py#L12)), so it is not ACKed by the device.

**Comment by matejcik** [comment]
okay, so does the device actually freeze (waiting for an answer; not recoverable by a follow-up message)?
because if yes, that's a Trezor side issue, that we can easily trigger by just not sending a message.

and if the freeze is recoverable by sending a different message, then I believe nothing on fw side needs to be done?

on the trezorlib side this seems covered -- the message that is too big is not actually sent, instead you see a RuntimeError.
it would be nice to implement a pre-check in EIP712 code to indicate that a message field is too big and won't go through, before the whole signing flow even starts

even so, the current handling should not lead to total freeze.

**Comment by zktex** [comment]
@Thalarion @danielhladik-sl Can you confirm this is reproducible in 2.11.1 please?

**Comment by fubuloubu** [comment]
Was testing this with my device (fw 2.9.5.0) using trezorlib 0.20.0, still getting an error that locks up device the same as before:

```py
site-packages/noise/connection.py:134, in NoiseConnection.encrypt(self, data)
    132     raise NoiseHandshakeError('Handshake not finished yet!')
    133 if not isinstance(data, bytes) or len(data) > MAX_MESSAGE_LEN:
--> 134     raise NoiseInvalidMessage('Data must be bytes and less or equal {} bytes in length'.format(MAX_MESSAGE_LEN))
    135 return self.noise_protocol.cipher_state_encrypt.encrypt_with_ad(None, data)

NoiseInvalidMessage: Data must be bytes and less or equal 65535 bytes in length
```

---

Updated the firmware to 2.11.1, still get the same issue. So, can confirm that it is not fixed w/ firmware 2.11.1, nor trezorlib 0.20.0

**Comment by M1nd3r** [comment]
@romanz Do you think it would be possible to resolve this issue in similar fashion as listing of FIDO credentials, i.e. making the potentially big message "streamed"? Alternatively, we can ressurect the "opportunistic creation of large (>8kB) send buffers". WDYT?

**Comment by fubuloubu** [comment]
> potentially big message "streamed"

Please, this would be amazing. I have run into many times when I've gone to sign a large SafeTx only to get blocked on this issue.

**Comment by romanz** [comment]
> THP encrypted protocol has a hard limit of 64 kB per packet, so this is unlikely to get fixed the proper way without a redesign of the EIP712 flow.

Agreed - currently we don't support splitting a single large struct field:
```
[2026-04-02 15:34:37,065] trezorlib.thp.client DEBUG: received message: EthereumTypedDataValueRequest
EthereumTypedDataValueRequest (4 bytes) {
    member_path: [1, 2],
}
[2026-04-02 15:34:37,065] trezorlib.thp.client DEBUG [s:1]: sending message: EthereumTypedDataValueAck
EthereumTypedDataValueAck (20004 bytes) {
    value: 20000 bytes b'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'...,
}
```
Also, [the device doesn't support >8kB protobuf messages to be received over THP](https://github.com/trezor/trezor-firmware/blob/766aafeb3b832197d280037e391000bf3061c9d8/core/src/trezor/wire/thp/memory_manager.py#L12).

**Comment by romanz** [comment]
> what we very much need to fix is the fact that it locks up the Trezor.

Tested locally using 2.10.0:
- ran `trezorctl eth sign-typed-data -n m/44h/60h/0h/0/0 sign-typed-data.json`[^1]
- the progress bar is shown - but the 20kB messages cannot get through.
- `trezorctl ping` results in a valid response from the device - i.e. it's not stuck.

[^1]: https://github.com/user-attachments/files/23860411/sign-typed-data.json.gz
